<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ConsultationMedicale extends \App\Entities\ConsultationMedicale implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'idConsultation', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'idDossierMedicale', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'typeConsultation', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'prescription', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'analyseComplementaire', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'diagnostique', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'dateVisite'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'idConsultation', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'idDossierMedicale', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'typeConsultation', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'prescription', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'analyseComplementaire', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'diagnostique', '' . "\0" . 'App\\Entities\\ConsultationMedicale' . "\0" . 'dateVisite'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ConsultationMedicale $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdConsultation()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdConsultation();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdConsultation', []);

        return parent::getIdConsultation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdConsultation($idConsultation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdConsultation', [$idConsultation]);

        return parent::setIdConsultation($idConsultation);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDossierMedicale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDossierMedicale', []);

        return parent::getIdDossierMedicale();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDossierMedicale($idDossierMedicale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDossierMedicale', [$idDossierMedicale]);

        return parent::setIdDossierMedicale($idDossierMedicale);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeConsultation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeConsultation', []);

        return parent::getTypeConsultation();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeConsultation($typeConsultation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeConsultation', [$typeConsultation]);

        return parent::setTypeConsultation($typeConsultation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrescription', []);

        return parent::getPrescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrescription($prescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrescription', [$prescription]);

        return parent::setPrescription($prescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnalyseComplementaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnalyseComplementaire', []);

        return parent::getAnalyseComplementaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnalyseComplementaire($analyseComplementaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnalyseComplementaire', [$analyseComplementaire]);

        return parent::setAnalyseComplementaire($analyseComplementaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiagnostique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiagnostique', []);

        return parent::getDiagnostique();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiagnostique($diagnostique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiagnostique', [$diagnostique]);

        return parent::setDiagnostique($diagnostique);
    }

}
