<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activite extends \App\Entities\Activite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'idActivite', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'nomActivite', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'descActivite', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'dateActivite', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'color', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'bgColor'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'idActivite', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'nomActivite', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'descActivite', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'dateActivite', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'color', '' . "\0" . 'App\\Entities\\Activite' . "\0" . 'bgColor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Activite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdActivite()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdActivite();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdActivite', []);

        return parent::getIdActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdActivite($idActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdActivite', [$idActivite]);

        return parent::setIdActivite($idActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomActivite', []);

        return parent::getNomActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomActivite($nomActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomActivite', [$nomActivite]);

        return parent::setNomActivite($nomActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescActivite', []);

        return parent::getDescActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescActivite($descActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescActivite', [$descActivite]);

        return parent::setDescActivite($descActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateActivite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateActivite', []);

        return parent::getDateActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateActivite($dateActivite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateActivite', [$dateActivite]);

        return parent::setDateActivite($dateActivite);
    }

    /**
     * {@inheritDoc}
     */
    public function getColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getColor', []);

        return parent::getColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setColor($color)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setColor', [$color]);

        return parent::setColor($color);
    }

    /**
     * {@inheritDoc}
     */
    public function getBgColor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBgColor', []);

        return parent::getBgColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setBgColor($bgColor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBgColor', [$bgColor]);

        return parent::setBgColor($bgColor);
    }

}
