<?php

namespace DoctrineProxies\__CG__\App\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DossierEnfant extends \App\Entities\DossierEnfant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'idDossierEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'nomEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'prenomEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'ageEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'dateNaissanceEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'origineEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'dateAjoutDossierEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'lieuNaissance', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'photoEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'profil', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'description', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'adresse'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'idDossierEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'nomEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'prenomEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'ageEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'dateNaissanceEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'origineEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'dateAjoutDossierEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'lieuNaissance', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'photoEnfant', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'profil', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'description', '' . "\0" . 'App\\Entities\\DossierEnfant' . "\0" . 'adresse'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DossierEnfant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdDossierEnfant()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDossierEnfant();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDossierEnfant', []);

        return parent::getIdDossierEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDossierEnfant($idDossierEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDossierEnfant', [$idDossierEnfant]);

        return parent::setIdDossierEnfant($idDossierEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEnfant', []);

        return parent::getNomEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEnfant($nomEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEnfant', [$nomEnfant]);

        return parent::setNomEnfant($nomEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomEnfant', []);

        return parent::getPrenomEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomEnfant($prenomEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomEnfant', [$prenomEnfant]);

        return parent::setPrenomEnfant($prenomEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgeEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgeEnfant', []);

        return parent::getAgeEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgeEnfant($ageEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgeEnfant', [$ageEnfant]);

        return parent::setAgeEnfant($ageEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissanceEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissanceEnfant', []);

        return parent::getDateNaissanceEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissanceEnfant($dateNaissanceEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissanceEnfant', [$dateNaissanceEnfant]);

        return parent::setDateNaissanceEnfant($dateNaissanceEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigineEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigineEnfant', []);

        return parent::getOrigineEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrigineEnfant($origineEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrigineEnfant', [$origineEnfant]);

        return parent::setOrigineEnfant($origineEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjoutDossierEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjoutDossierEnfant', []);

        return parent::getDateAjoutDossierEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuNaissance', []);

        return parent::getLieuNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuNaissance($lieuNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuNaissance', [$lieuNaissance]);

        return parent::setLieuNaissance($lieuNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfil', []);

        return parent::getProfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfil($profil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfil', [$profil]);

        return parent::setProfil($profil);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjoutDossierEnfant($dateAjoutDossierEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjoutDossierEnfant', [$dateAjoutDossierEnfant]);

        return parent::setDateAjoutDossierEnfant($dateAjoutDossierEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoEnfant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoEnfant', []);

        return parent::getPhotoEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoEnfant($photoEnfant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoEnfant', [$photoEnfant]);

        return parent::setPhotoEnfant($photoEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

}
